language: c
# For doc-building dependencies.
cache: pip
  
addons:
  apt:
    packages:
      - tk-dev
      - liblzma-dev
      - python-pip

compiler:
  - clang
  - gcc

env:
  - TESTING=cpython
      
matrix:
  include:
    - os: linux
      language: python
      python: 3.5
      env: TESTING=docs

script:
  - if [[ "$TESTING" == "cpython" ]]; then ./configure --with-pydebug && make -j && ./python -bb -E -W default -m test -r -w -uall -j0 ; fi
  - if [[ "$TESTING" == "docs" ]]; then cd Doc && make venv PYTHON=python3 && make html SPHINXBUILD="./venv/bin/python3 -m sphinx" SPHINXOPTS="-nW -q -b linkcheck" ; fi

notifications:
  email: false
