language: c
# For doc-building dependencies.
cache: pip

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
      - tk-dev
      - liblzma-dev
      - python-pip

# Would rather use Python 3 and `make venv`, but not sure how to get it installed in the container easily.
before_script: pip install --user -U sphinx  

script:
  - ./configure --with-pydebug && make -j && ./python -bb -E -W default -m test -r -w -uall -j0
  - cd Doc && make html SPHINXOPTS="-nW -q -b linkcheck"

# Since this is just a demo repository, we don't want people who may not even
# be involved in the demo to get an email when build fail.
notifications:
  email: false
